#!/bin/sh

PROGRAM="/usr/bin/edge-gateway"
PIDFILE="/var/run/edge-gateway.pid"
LOGFILE="/var/log/edge-gateway.log"

case "$1" in
    start)
        echo "Starting edge gateway"

        start-stop-daemon \
            -S \
            -b \
            -m \
            -p "$PIDFILE" \
            -x "$PROGRAM" \
            -- >> "$LOGFILE" 2>&1
        ;;

    stop)
        echo "Stopping edge gateway"

        start-stop-daemon \
            -K \
            -p "$PIDFILE" \
            -x "$PROGRAM"

        rm -f "$PIDFILE"
        ;;

    restart)
        "$0" stop
        sleep 1
        "$0" start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
